[package]
name = "router"
version = "0.1.0"
authors = ["Luke Steensen <luke.steensen@gmail.com>"]

[dependencies]
fern = "0.5.6"
log = "0.4.5"
byteorder = "1.2.6"
tempdir = "0.3.7"
uuid = { version = "0.7.1", features = ["v4"] }
memchr = "2.1.0"
chrono = "0.4.6"
rand = "0.5.5"
regex = "1.0.5"
duct = "0.11.1"
os_pipe = "0.8.0"
bytes = "0.4.10"
tokio = "0.1.11"
futures = "0.1.25"
